baseURL = "https://github.com/smillerc/smillerc.github.io"
languageCode = "en-us"
title = "Scientific Development"
theme = "hugo-vitae"
paginate = 5

copyright = "© Copyright Sam Miller, 2020 | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# googleAnalytics = "UA-123-45"

[taxonomies]
	tag = "tags"
	series = "series"

[params]
	subtitle = "A blog about fluid dynamics and scientific development"

	# Optional 80x80 avatar image.
	# avatar = "/img/vitae.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[[menu.main]]
name = "Links"
url = "/links"
weight = 3

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/smillerc"

[[params.social]]
name = "ResearchGate"
icon = "fab fa-researchgate"
url = "https://www.researchgate.net/profile/Samuel_Miller2"

[[params.social]]
name = "ORCiD"
icon = "fab fa-orcid"
url = "https://orcid.org/0000-0001-6452-2308"
